### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by BrixSat** [Ovid/DB--Color#4]
When doing a debug with the db-color enabled the execution is very very very slow, on some files it took me 10 minutes to open having 100% cpu.

**Comment by Ovid** [comment]
You might want to checkout out version 0.20. In particular, [checkout out the `WORKFLOW` section in the pod](https://github.com/Ovid/DB--Color/blob/master/lib/DB/Color.pm#L81).

I've added support for a sentinel file (only load `DB::Color` as needed). There is also a new `examples/colorize` program which you can use to create a daemon which will colorize files for you, before you enter the debugger.
